<?php
  $pageTitle = "Guide to Submitting a Video as Supplementary Material";
  include "../header.php";
?>

<div >
<h2 >Guide to Submitting a Video as Supplementary Material</h2>
</div>

<div >
<p>This guide provides information for preparing a supplementary digital video for submission to any of the CHI venues where videos are accepted. For submissions to the video showcase, please see the&nbsp;<a href="http://chi2015.acm.org/authors/video-showcase" >Video Showcase Call for Participation</a>.</p>
<h3 >Technical Requirements</h3>
<h4 >Size</h4>
<p>A submission that includes a supplementary digital video must not exceed 100 MB in total size (paper + video) for it to be included in the ACM Digital Library.</p>
<h4 >Format</h4>
<p>We strongly suggest an MP4 encoding using the H.264 codec for your digital video submission. Most video editing software provides an exporting option to MP4/H.264, for example iMovie, Adobe Premiere, Camtasia, and Final Cut Pro. If you prefer to use free software,&nbsp;<a href="http://www.videohelp.com/tools/x264-Encoder"  target="_blank">x264</a>&nbsp;can encode any video into H.264. If you compress your video with unusual software or codecs you risk the distinct possibility that reviewers will not be able to watch your clip, and it may need to be re-encoded for the conference disc. CHI does not accept analog (videotape) submissions, software applications (.exe files), or digital video clips requiring a specific computing platform or additional software to play.</p>
<p>We strongly recommend 16:9 aspect ratio. Encode your video using square pixels for the pixel aspect ratio to avoid your movie looking stretched when projected.</p>
<h4 >Duration</h4>
<p>Supplementary video figures do not have a specified limit for duration, although we recommend staying within 5 minutes. If you plan to play the figure during your conference presentation, be sure that you allow enough time both for the video and the other portions of the presentation, including time at the end for questions.</p>
<h4 >Identification</h4>
<p>Please remember to review the meta-data properties of your digital file. For submission to an anonymized venue, all meta-data that could identify the authors should be removed. The camera ready version of your video submission should contain a title slide with the title, authors, and affiliations. Authors retain copyright of videos but ACM requires that you sign an agreement allowing ACM to distribute the material.</p>
<h3 >Preparation Suggestions</h3>
<p>This section contains guidelines and hints for those who are new to video production, particularly in creating videos for CHI. None of the following suggestions are required reading.</p>
<h4 >Organization and Structure</h4>
<p>There are many ways to organize a video presentation, just as there are many ways to write prose. You should select a theme for the video and present the research in a way that contributes to this goal. It is generally not a good idea to simply show all the features of your system; you should identify what is novel and interesting. Emphasize the problems or issues being addressed. Present the concepts and principles upon which the work is based. Always clearly state the status of what is being shown. If you are simulating any aspect of the system, be sure to mention this.</p>
<p>Your video should be understandable by itself. You should not assume that the viewer has read your printed submission. Therefore, most videos will need a short introduction explaining the goals and context of the work. Your video should also be understandable to viewers who are not familiar with the subject.</p>
<h4 >Exposition and Presentation</h4>
<p>The exposition style of your video presentation will greatly affect its impact. Use both the visual and audio capabilities of video. Always explain what is about to happen or what is most interesting: as the narrator, tell the viewer where to look and what to look for. Visual aids, such as callouts, annotations and captions, can help orient the viewer. Make your point once, and make it effectively; avoid being repetitious.</p>
<p>When appropriate, seek a variety of images: switch between face, screen, hands, and slides to keep the viewer’s interest. If possible, start out with an establishing shot, which shows the context of the subject and/or group. This might be a wide shot of the group in a meeting room, a split-screen shot of users in different locations, a wide shot of a meeting participant at the computer or of the entire computer screen. This helps the viewer stay oriented. Periodically return to an establishing shot to prevent viewer confusion.</p>
<p>Each shot should be visually well composed. Avoid having the subject in the exact middle of the screen. Pay attention to the background and colors; the eye is drawn to the most brightly colored part of the scene. Make the lightest and brightest part be the point of interest. Carefully consider lighting and make sure that there are no distracting shadows, especially on faces (a common occurrence with overhead lighting).</p>
<p>Do not overuse panning, zooming and other moving shots. Begin and end each moving shot with a static shot. Avoid visual distractions, such as idly moving the mouse. Fades to black can be used as transitions between scenes, but they should not be overused. A full screen fade usually indicates a change in subject, time or place, and can be confusing when used elsewhere.</p>
<h4 >Pacing</h4>
<p>Video is different from a lecture or a demonstration. The pacing of a video presentation must be appropriate: too slow a pace is as common as too fast. A recording of a live demonstration will appear too slow. A large number of jump cuts (abrupt change of image) may create too fast a pace. And please remember that your digital video will be accessed by an international audience, so speak clearly and more slowly than is natural to successfully convey your message.</p>
<p>Your video need not employ professional actors, although you may wish to use professional readers to obtain the best audio results. Usually the most realistic and convincing advocate of an idea is the person responsible for the work being reported. Whoever appears before the camera should remember to speak naturally and don’t appear to be reading. Try to keep “talking heads” (close up shot of a person talking) to a minimum.</p>
<h4 >Equipment and Techniques</h4>
<p>Before recording begins, prepare a detailed script of the video and rehearse it thoroughly. Videos require much more planning and preparation than most people think. For your rehearsal, find someone who doesn’t understand what you do and make your presentation to them. This will provide good practice in speaking and help to clarify the delivery of your ideas. If your presentation involves a larger group of people it will be especially important to have the script you will speak and the production process you will use worked out in advance.</p>
<p>The final production quality of a video depends both on the quality of the equipment and the training and experience of the video maker. If you have access to a high-quality production studio and trained personnel, use them. However, suitable production quality can be achieved with the equipment found in most universities, companies, and homes.</p>
<h4 >Camera Basics</h4>
<p>Maintain the quality of the original recording medium throughout the editing process by saving compression for the final version.</p>
<p>Keeping the camera stable and level is vital. Use a tripod whenever possible. Remember that camera jiggles are more apparent in telephoto shots; take extra care in zooms and close-ups.</p>
<p>You will produce better results if you monitor your recording on a large monitor in addition to the viewfinder of the camera. Using a monitor will greatly help you determine whether your shots are correct. Remember that the final picture will not be as clear as the picture in the monitor, so zoom in closer than might seem necessary, and make sure that no important elements are at the edge of the picture.</p>
<h4 >Audio</h4>
<p>Audio quality is as important as image quality to the overall impact of your video. Try to avoid recording the noise of computer fans and disks. It is generally better to record the audio separately, by doing a voice-over in a studio or other quiet room. With a voice-over, you watch the video and record the sound that explains what is happening. Make sure that the discussion is synchronized with the action on the screen. If you have introductory “talking heads,” try to do these with the computer off, or with the microphones arranged so that the computer noise is not picked up. Another motivation for doing a voice-over afterwards is that the person operating the computer can concentrate on the demo and go as fast as possible without awkward pauses while he or she thinks about what to say next. Many successful videos use trained readers for the audio, which you can find by calling acting schools or radio stations.</p>
<p>If it is important to hear key clicks or computer audio output (beeps), record these on a separate audio track, and mix them with the voice-over in your editing software. Similarly, if you are adding music to the video, place it on a separate track, so it will be easy to fade out music when narration begins, etc.</p>
<h4 >Recording Computer Screens</h4>
<p>Because of incompatibilities of resolution, refresh rate, and interlacing, it can be difficult to get good shots of computer screens on video. As such, we highly recommend recording video of a computer screen using screen capture software, such as Camtasia.</p>
<p>If you are using screen capture software, make sure that it is able to capture the screen at a satisfactory frame rate and does not affect the performance of your application. Most software can capture the whole screen or a specific area such as a window. Since performance is often affected by the size of the area being captured, you should try to focus the capture on the area of interest. This will also reduce the artifacts if you later compress and rescale the image. Finally, remember that screen capture only captures the screen (!): you may want to add wider shots taken with a camcorder to show the user interacting with the system; you should also consider adding click sounds when the user clicks the mouse to make such interactions more explicit (some capture software can do that automatically).</p>
<h4 >Editing</h4>
<p>Raw analog or digital footage can be 1 gigabyte per minute in data size. Editing digital video generally requires twice the disk space as the video itself. Choose what you want to preserve carefully when editing, and compress your video as a final step.</p>
<h4 >Usability Testing</h4>
<p>They say that the children of shoemakers have no shoes, and that people at the human factors and ergonomics conference tend to use illegible slides! Participants in HCI conferences and publications need to make sure that their presentations and products are usable. Please test your video for usability just as you would any other product. You can start off by testing your script with colleagues and friends. Is it interesting and understandable? Next you may want to storyboard your video. Do the cuts and transitions make sense; can you visualize how it will look? As well as being useful for usability testing, the storyboard should be an important part of your planning process. Next you should do rough cuts of the video. Do people want to see more talking head shots or fewer? Is the illustration of your material clear? Is the pace too fast or too slow? Are there any particular usability problems with specific segments of the video?</p>
<p>Anyone who has done video editing and post-production knows that it is a surprisingly time consuming business. Moreover, if you don’t have good content or a clear message, excellent editing will not make an excellent video. Please ensure that you thoroughly usability test your video, including a final test to ensure that your digital video file will play on a variety of computers.</p>
<hr>
<p>This document has drawn heavily on the Guides for Submission written by previous CHI and CSCW video chairs, originally published on the CHI ’99 Conference website. Portions of the UIST video guide have also been used. If you have any questions, please contact the Technical Program Chairs at&nbsp;<a href="mailto:technicalprogram@chi2015.acm.org"  target="_blank">technicalprogram@chi2015.acm.org</a>.</p>
</div>

<?php
  include "../footer.php";
?>
