<?php
  $pageTitle = "Guide to Reviewing CHI Papers and Notes";
  include "../header.php";
?>

<div >
<h2 >Guide to Reviewing CHI Papers and Notes</h2>
</div>

<div >
<p>The CHI review process for 2015 will continue to make use of the subcommittee structure introduced for CHI 2009. The key points in undertaking reviews are:</p>
<ul><li>Your primary criterion for judging a paper is: Does this submission provide a strong contribution to the field of HCI? Please remember that there are many ways for which a paper can make a contribution to HCI, and you should review the paper appropriately. See:&nbsp;<a href="http://chi2015.acm.org/authors/contributions-to-hci" >Contributions to HCI</a>&nbsp;for details.</li>
<li>In recognition that there are a range of different types of expertise in our field, and in an attempt to have each paper judged by true experts in its topic, authors submit their papers to subcommittees which are clustered around different topics (see:&nbsp;<a href="http://chi2015.acm.org/authors/selecting-a-subcommittee" >Selecting a subcommittee</a>). However, matches of papers to subcommittees are not always clean or perfect. So as a reviewer you should not judge a paper by how well it fits the subcommittee theme.</li>
<li>Reviewers rate the paper using a 5-point ranking scale; your written appraisal must support your numeric ranking.</li></ul>
<h3 >Subcommittees</h3>
<p>To improve the reviewing process, authors submit their papers to sub-committees that best reflect their most salient contribution, where each sub-committee is responsible for various topic areas typically seen at CHI (see:&nbsp;<a href="http://chi2015.acm.org/authors/selecting-a-subcommittee" >Selecting a subcommittee</a>&nbsp;for details). Each sub-committee will comprise of a sub-chair and associate chairs who are knowledgeable in these topics. The idea is that, as specialists in the theme areas, they should be able to find good referees (such as you) for each submission, and that as specialists they should be able to better handle the meta-review process.</p>
<p>However, as a reviewer,&nbsp;<strong>you should not judge the paper by how well it fits the subcommittee theme(s)</strong>. Many papers will not cleanly fit into a particularly sub-committee for a variety of reasons, and we do not want to penalize authors for this. Remember, the subcommittee organization is there only to try to improve reviewer matches and to better handle the volume of submissions. If you have a paper that does not fit the subcommittee theme,&nbsp;<strong>evaluate it as best you can with respect to its own quality</strong>. Any topic is valid, as long as it fits within the interests of a reasonable fraction of the overall CHI audience -&nbsp;<strong>the primary criterion remains the contribution to HCI</strong>.</p>
<h3 >Contributions</h3>
<p>The primary criterion for evaluation of all Papers and Notes is the research's contribution to HCI. In all cases, a CHI Paper or Note must break new ground and make an original research contribution. However, it is important to recognize that there are many ways for which a paper can make a contribution to HCI, and you should review the paper appropriately. Please see&nbsp;<a href="http://chi2015.acm.org/authors/contributions-to-hci" >Contributions to HCI</a>&nbsp;for a list of some of the types of contributions a paper can make to HCI, and the associated criteria that you can use to assess this type of contribution.</p>
<h3 >Papers and Notes</h3>
<p>Papers and Notes are both reviewed within the same rigorous review process and at the highest level are judged by very similar criteria&nbsp;<i>(i.e., does this paper or note provide a strong contribution to the field of HCI?)</i>. However, it is important as a reviewer to realize that the type of content that is appropriate for each is somewhat different. In particular, Notes present brief and focused research contributions that are noteworthy, but may not be as comprehensive or provide the same depth of results as a full paper. For details about these differences see&nbsp;<a href="http://chi2015.acm.org/authors/papers-versus-notes" >Papers versus Notes: What is the difference?</a></p>
<h3 >Numeric Ratings and Written Appraisals</h3>
<p>The numeric ratings on the review form are on a 5 point scale (with half steps) starting at 1.0 (the lowest ratings) to 5.0 (the highest). Be as accurate with your ratings as possible. As in previous years, it is your written appraisal that is crucial. Make sure your review is&nbsp;<strong>balanced</strong>, and that its details reflect the numeric rating. The appraisal of a paper should&nbsp;<strong>always indicate why the paper deserves that rating</strong>. Your review may be discounted if, for example, you numerically rate a paper highly but only indicate its flaws. As well,&nbsp;<strong>please be polite</strong>&nbsp;to authors. Even if you rate a paper poorly, you can critique it in a positive voice. As part of polite reviewing practice, you should always<strong>state what is good about a paper first</strong>, followed by your&nbsp;<strong>criticisms</strong>. If possible, you should offer&nbsp;<strong>suggestions for improvement</strong>&nbsp;along with your criticism.</p>
<h3 >Prior Publication</h3>
<p>Content appearing at CHI should be new and ground-breaking. Therefore, material that has been previously published in widely disseminated publications should not be republished unless the work has been "significantly" revised. Guidelines for determining "significance" of a revision are stated in the&nbsp;<a href="http://www.acm.org/publications/policies/prepub_eval"  target="_blank">ACM Policy on Pre-Publication Evaluation</a> and the&nbsp;<a href="http://www.acm.org/publications/policies/sim_submissions/"  target="_blank">ACM Policy on Prior Publication and Simultaneous Submissions</a>. Roughly, a significant revision would contain more than 25% new content material (i.e., material that offers new insights, new results, etc.) and significantly amplify or clarify the original material. These are subjective measures left to the interpretation and judgment of the reviewers and committee members - authors are advised to revise well beyond the Policy guidelines.</p>
<p>An exception is for work that has previously been presented or published in a language other than English. Such work may be translated and published in English at CHI. The original author should typically also be the author (or co-author) of work translated into English and it should be made clear that this is a translation. For more information see: <a href="http://www.sigchi.org/conferences"  target="_blank">http://www.sigchi.org/conferences</a>.</p>
<h3 >References</h3>
<p>The debate about what makes a good CHI paper has been ongoing for several years. If you are interested, the papers below touch upon this debate and contain references to additional papers that concern it.</p>
<ul><li>Greenberg, S. and Buxton, B. 2008. Usability evaluation considered harmful (some of the time). In Proceeding of the Twenty-Sixth Annual SIGCHI Conference on Human Factors in Computing Systems. CHI '08. ACM, 111-120. DOI=<a href="http://doi.acm.org/10.1145/1357054.1357074"  target="_blank">http://doi.acm.org/10.1145/1357054.1357074</a></li>
<li>Olsen, D. R. 2007. Evaluating user interface systems research. In Proceedings of the 20th Annual ACM Symposium on User interface Software and Technology. UIST '07. ACM, 251-258. DOI=<a href="http://doi.acm.org/10.1145/1294211.1294256"  target="_blank">http://doi.acm.org/10.1145/1294211.1294256</a></li>
<li>Dourish, P. 2006. Implications for design. In Proceedings of the SIGCHI Conference on Human Factors in Computing Systems. CHI '06, ACM, 541-550. DOI=<a href="http://doi.acm.org/10.1145/1124772.1124855"  target="_blank">http://doi.acm.org/10.1145/1124772.1124855</a></li>
<li>Newman, W. 1994. A preliminary analysis of the products of HCI research, using pro forma abstracts. In Proceedings of the SIGCHI Conference on Human Factors in Computing Systems: Celebrating interdependence (Boston, Massachusetts, United States, April 24 - 28, 1994). ACM, New York, NY, 278-284. DOI=<a href="http://doi.acm.org/10.1145/191666.191766"  target="_blank">http://doi.acm.org/10.1145/191666.191766</a></li>
<li>Daniel Reed and Ed H. Chi. 2012. Online privacy; replicating research results. Commun. ACM 55, 10 (October 2012), 8-9. DOI=<a href="http://doi.acm.org/10.1145/2347736.2347739"  target="_blank">http://doi.acm.org/10.1145/2347736.2347739</a></li></ul>
</div>

<?php
  include "../footer.php";
?>